/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011-2012 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::radiation::isotropicPhaseFunc

Description
    Isotropic phase function

SourceFiles
    isotropicPhaseFunc.C

\*---------------------------------------------------------------------------*/

#ifndef radiationIsotropicPhaseFunc_H
#define radiationIsotropicPhaseFunc_H

#include "phaseFuncModel.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
namespace radiation
{

/*---------------------------------------------------------------------------*\
                  Class isotropicPhaseFunc Declaration
\*---------------------------------------------------------------------------*/

class isotropicPhaseFunc
:
    public phaseFuncModel
{
    // Private data

        //- Scattering isotropic factor
		scalar factor_;

public:

    //- Runtime type information
    TypeName("isotropicPhaseFunction");


    // Constructors

        //- Construct from components
        isotropicPhaseFunc(const dictionary& dict, const fvMesh& mesh);


    //- Destructor
    virtual ~isotropicPhaseFunc();

	    //Scattering Matrix Generation
	    void MatrixGen(const List<vector> directions, const label model);
		
		scalar sctrFactor(const label model, const label band, const label directionFrom, const label directionTo) const;
				
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace radiation
} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
